// Auto-generated by Lerma Map Maker — 2026-04-02T10:21:13.783Z
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
const __dirname = dirname(fileURLToPath(import.meta.url));

export const ZONES = {
  lerma: {
    id:'lerma',
    name:'Barangay Lerma',
    mapFile:'lerma.json',
    portals:[
      { x:0, y:20, destZone:'panganiban', destX:58, destY:20, label:'Panganiban ←' },
      { x:59, y:20, destZone:'diversion', destX:1, destY:20, label:'Diversion →' }
    ],
    migs:{ x:30, y:20 },
    defaultSpawn:{x:30,y:20},
  },
  panganiban: {
    id:'panganiban',
    name:'Panganiban',
    mapFile:'panganiban.json',
    portals:[
      { x:59, y:20, destZone:'lerma', destX:1, destY:20, label:'Lerma →' },
      { x:30, y:39, destZone:'plaza_rizal', destX:30, destY:1, label:'Plaza Rizal ↓' }
    ],
    migs:null,
    defaultSpawn:{x:30,y:20},
  },
  plaza_rizal: {
    id:'plaza_rizal',
    name:'Plaza Rizal',
    mapFile:'plaza_rizal.json',
    portals:[
      { x:30, y:0, destZone:'panganiban', destX:30, destY:38, label:'Panganiban ↑' },
      { x:0, y:20, destZone:'bagumbayan', destX:58, destY:20, label:'Bagumbayan ←' }
    ],
    migs:{ x:30, y:20 },
    defaultSpawn:{x:30,y:20},
  },
  diversion: {
    id:'diversion',
    name:'Diversion Road',
    mapFile:'diversion.json',
    portals:[
      { x:0, y:20, destZone:'lerma', destX:58, destY:20, label:'Lerma ←' },
      { x:30, y:39, destZone:'tabuco', destX:30, destY:1, label:'Tabuco ↓' }
    ],
    migs:null,
    defaultSpawn:{x:30,y:20},
  },
  tabuco: {
    id:'tabuco',
    name:'Tabuco',
    mapFile:'tabuco.json',
    portals:[
      { x:30, y:0, destZone:'diversion', destX:30, destY:38, label:'Diversion ↑' }
    ],
    migs:{ x:30, y:20 },
    defaultSpawn:{x:30,y:20},
  },
  bagumbayan: {
    id:'bagumbayan',
    name:'Bagumbayan',
    mapFile:'bagumbayan.json',
    portals:[
      { x:59, y:20, destZone:'plaza_rizal', destX:1, destY:20, label:'Plaza Rizal →' },
      { x:0, y:20, destZone:'liboton', destX:58, destY:20, label:'Liboton ←' }
    ],
    migs:null,
    defaultSpawn:{x:30,y:20},
  },
  liboton: {
    id:'liboton',
    name:'Liboton',
    mapFile:'liboton.json',
    portals:[
      { x:59, y:20, destZone:'bagumbayan', destX:1, destY:20, label:'Bagumbayan →' },
      { x:30, y:0, destZone:'francia', destX:30, destY:38, label:'Francia ↑' }
    ],
    migs:null,
    defaultSpawn:{x:30,y:20},
  },
  francia: {
    id:'francia',
    name:'Francia',
    mapFile:'francia.json',
    portals:[
      { x:30, y:39, destZone:'liboton', destX:30, destY:1, label:'Liboton ↓' },
      { x:0, y:20, destZone:'san_felipe', destX:58, destY:20, label:'San Felipe ←' }
    ],
    migs:{ x:30, y:20 },
    defaultSpawn:{x:30,y:20},
  },
  san_felipe: {
    id:'san_felipe',
    name:'San Felipe',
    mapFile:'san_felipe.json',
    portals:[
      { x:59, y:20, destZone:'francia', destX:1, destY:20, label:'Francia →' }
    ],
    migs:null,
    defaultSpawn:{x:30,y:20},
  },
  concepcion: {
    id:'concepcion',
    name:'Concepcion',
    mapFile:'concepcion.json',
    portals:[

    ],
    migs:null,
    defaultSpawn:{x:30,y:20},
  }
};

const mapCache = {};
export function getZoneMap(zoneId) {
  if (mapCache[zoneId]) return mapCache[zoneId];
  const zone = ZONES[zoneId];
  if (!zone) throw new Error(`Unknown zone: ${zoneId}`);
  const data = JSON.parse(readFileSync(join(__dirname, 'zones', zone.mapFile), 'utf8'));
  const blockedSet = new Set(data.blocked || []);
  const map = { w:data.w, h:data.h, tiles:data.tiles, isBlocked:(x,y)=>blockedSet.has(`${x},${y}`) };
  mapCache[zoneId] = map;
  return map;
}
export function checkPortal(zoneId, x, y) {
  const zone = ZONES[zoneId];
  if (!zone) return null;
  return zone.portals.find(p => p.x === x && p.y === y) || null;
}
